### ISSUE TITLE
Please release new version of optimizely on rubygems

### ISSUE THREAD

**Issue by thomasdziedzic** [MartijnSch/optimizely-gem#2]
Also, please tag the release.

There have been enough changes imo to justify a new release.

**Comment by MartijnSch** [comment]
Sorry Thomas, my bad. Forgot to do this earlier, will push a new version later on.

**Comment by MartijnSch** [comment]
Fixed.

**Comment by thomasdziedzic** [comment]
Could you also push a 1.2.2 tag into github so that we have a record of what code was in 1.2.2?
